### ISSUE TITLE
Performance flaw

### ISSUE THREAD

**Issue by fvonellerts** [flowck/vue-cobra#3]
First of all, thanks for taking the time to create this package.

Too bad I just discovered a major performance flaw: You set `width` on scroll.

This invalidates the whole layout **every scroll** (https://csstriggers.com/width)!
It is way more costly than using `transform: scaleX` which only mutates the composite layer (https://csstriggers.com/transform). This difference becomes visible when doing other rendering operations like CSS transitions.

Should be a really quick fix. `will-change: transform` could also help.

**Comment by flowck** [comment]
Hi @fvonellerts, thanks for opening an issue. 

Would you mind to send a pull request?

Thank you.
