### ISSUE TITLE
Option for vertical scroll progress bar

### ISSUE THREAD

**Issue by ptrvc** [flowck/vue-cobra#5]
Would be really nice to have an option to change the scroll progress bar from horizontal one to vertical one, as on here: https://jurajmolnar.com

**Comment by flowck** [comment]
Hi @ptrvc, thanks for the suggestion. It's already possible to change the progress bar position through `:position="left"` or `:position="bottom"` starting from: https://github.com/flowck/vue-cobra/pull/6.
